import { Certification } from "@/types/certification";

export const certifications: Certification[] = [
  {
    id: "hcia-ai-v4",
    name: "HCIA-AI V4.0 (Huawei Certified ICT Associate – Artificial Intelligence)",
    issuer: "Huawei",
    date: "2025-10",
    badgeImage: undefined,
    verifyUrl: "/certifications/hcia-ai-v4.pdf",
  },
  {
    id: "hcia-ai-v4-colombia",
    name: "HCIA-AI V4.0 – Colombia Training Program",
    issuer: "Huawei",
    date: "2025-10",
    badgeImage: undefined,
    verifyUrl: "/certifications/hcia-ai-v4-colombia.pdf",
  },
  {
    id: "hcia-cloud-computing",
    name: "HCIA-Cloud Computing V5.5",
    issuer: "Huawei",
    date: "2025-10",
    badgeImage: undefined,
    verifyUrl: "/certifications/hcia-cloud-computing-v5.pdf",
  },
  {
    id: "hcia-cloud-service",
    name: "HCIA-Cloud Service V3.5",
    issuer: "Huawei",
    date: "2025-10",
    badgeImage: undefined,
    verifyUrl: "/certifications/hcia-cloud-service-v3.pdf",
  },
  {
    id: "kubernetes-lfs158",
    name: "Introduction to Kubernetes (LFS158)",
    issuer: "The Linux Foundation",
    date: undefined,
    badgeImage: "/certifications/kubernetes-lfs158-badge.png",
    verifyUrl: "/certifications/linux-foundation-lfs158.pdf",
  },
  {
    id: "blockchain-basics",
    name: "Blockchain Basics",
    issuer: "Cyfrin Updraft",
    date: "2026-07",
    badgeImage: "/certifications/blockchain-basics-badge.webp",
    verifyUrl: undefined,
  },
  {
    id: "systems-analysis-ibm",
    name: "Systems Analysis Essentials",
    issuer: "IBM",
    date: "2026-03",
    badgeImage: "/certifications/systems-analysis-badge.png",
    verifyUrl: "/certifications/systems-analysis.pdf",
  },
  {
    id: "digital-entrepreneurship-afrilabs",
    name: "Digital Entrepreneurship Skills",
    issuer: "AfriLabs",
    date: "2025-03",
    badgeImage: undefined,
    verifyUrl: "/certifications/digital-entrepreneurship.pdf",
  },
  {
    id: "everyday-excel",
    name: "Everyday Excel",
    issuer: "Coursera",
    date: "2025-09",
    badgeImage: "/certifications/excel-badge.jpeg",
    verifyUrl: undefined,
  },
  {
    id: "kuwaelimika",
    name: "Kuwaelimika Kwa Afrika",
    issuer: "Kuwaelimika",
    date: undefined,
    badgeImage: undefined,
    verifyUrl: "/certifications/kuwaelimika.pdf",
  },
];

